#base image for the docker file
#users start building their own image by using this dockerfile
FROM spark77/faasr

#users should add their own Rscripts into /action/ - directory can be changable
ADD example.R /action/
